server:
  port: ${PORT:8090}

vaadin:
  launch-browser: 'false'
  allowed-packages: com.vaadin,org.vaadin,io.binarycodes.vaadin

spring:
  mustache:
    check-template-location: 'false'
  jpa:
    defer-datasource-initialization: 'true'


logging:
  level:
    org:
      atmosphere: warn